version: '3.8'

services:
  comfyui:
    build:
      context: ./Comfyui
      dockerfile: Dockerfile
    image: ${IMAGE_NAME}
    container_name: comfyui
    ports:
      - "8188:8188"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ${VOLUME_ROOT}:/comfyui_docker
